- version 1.10
Changed files:
    happy-DESTDIR.patch -> 1.2
    happy.spec -> 1.2

diff --git a/happy-DESTDIR.patch b/happy-DESTDIR.patch
--- a/happy-DESTDIR.patch
+++ b/happy-DESTDIR.patch
@@ -1,20 +1,47 @@
---- happy-1.8/mk/target.mk~	Tue Jun 20 13:22:21 2000
-+++ happy-1.8/mk/target.mk	Sat Nov 18 03:53:00 2000
-@@ -603,10 +603,10 @@
+--- ./mk/target.mk.org	Sun Jun 24 12:25:02 2001
++++ ./mk/target.mk	Sun Jun 24 12:34:01 2001
+@@ -686,13 +686,13 @@
  # on perl.
  #
- $(SCRIPT_LINK) : $(SCRIPT_PROG)
--	@if ( $(PERL) -e '$$fn="$(SCRIPT_LINK)"; exit ((! -f $$fn || -l $$fn) ? 0 : 1);' ); then \
-+	@if ( $(PERL) -e '$$fn="$(DESTDIR)$(SCRIPT_LINK)"; exit ((! -f $$fn || -l $$fn) ? 0 : 1);' ); then \
- 	   echo "Creating a symbolic link from $(SCRIPT_PROG) to $(SCRIPT_LINK)"; \
--	   $(RM) $(SCRIPT_LINK); \
--	   $(LN_S) $(SCRIPT_PROG) $(SCRIPT_LINK); \
-+	   $(RM) $(DESTDIR)$(SCRIPT_LINK); \
-+	   $(LN_S) $(SCRIPT_PROG) $(DESTDIR)$(SCRIPT_LINK); \
+ $(LINK) : $(LINK_TARGET)
+-	@if ( $(PERL) -e '$$fn="$(LINK)"; exit ((! -f $$fn || -l $$fn) ? 0 : 1);' ); then \
++	@if ( $(PERL) -e '$$fn="$(DESTDI)$(LINK)"; exit ((! -f $$fn || -l $$fn) ? 0 : 1);' ); then \
+ 	   echo "Creating a symbolic link from $(LINK_TARGET) to $(LINK)"; \
+-	   $(RM) $(LINK); \
+-	   $(LN_S) $(LINK_TARGET) $(LINK); \
++	   $(RM) $(DESTDIR)$(LINK); \
++	   $(LN_S) $(LINK_TARGET) $(DESTDIR)$(LINK); \
  	 else \
- 	   echo "Creating a symbolic link from $(SCRIPT_PROG) to $(SCRIPT_LINK) failed: \`$(SCRIPT_LINK)' already exists"; \
- 	   echo "Perhaps remove \`$(SCRIPT_LINK)' manually?"; \
-@@ -652,10 +652,10 @@
+-	   echo "Creating a symbolic link from $(LINK_TARGET) to $(LINK) failed: \`$(LINK)' already exists"; \
+-	   echo "Perhaps remove \`$(LINK)' manually?"; \
++	   echo "Creating a symbolic link from $(LINK_TARGET) to $(DESTDIR)$(LINK) failed: \`$(DESTDIR)$(LINK)' already exists"; \
++	   echo "Perhaps remove \`$(DESTDIR)$(LINK)' manually?"; \
+ 	   exit 1; \
+ 	 fi;
+ 
+@@ -701,14 +701,14 @@
+ # install links to script drivers.
+ #
+ install ::
+-	@$(INSTALL_DIR) $(bindir)
+-	@if ( $(PERL) -e '$$fn="$(bindir)/$(LINK)"; exit ((! -f $$fn || -l $$fn) ? 0 : 1);' ); then \
+-	   echo "Creating a symbol link from $(LINK_TARGET) to $(LINK) in $(bindir)"; \
+-	   $(RM) $(bindir)/$(LINK); \
+-	   $(LN_S) $(LINK_TARGET) $(bindir)/$(LINK); \
++	@$(INSTALL_DIR) $(DESTDIR)$(bindir)
++	@if ( $(PERL) -e '$$fn="$(DESTDIR)$(bindir)/$(LINK)"; exit ((! -f $$fn || -l $$fn) ? 0 : 1);' ); then \
++	   echo "Creating a symbol link from $(LINK_TARGET) to $(LINK) in $(DESTDIR)$(bindir)"; \
++	   $(RM) $(DESTDIR)$(bindir)/$(LINK); \
++	   $(LN_S) $(LINK_TARGET) $(DESTDIR)$(bindir)/$(LINK); \
+ 	 else \
+-	   echo "Creating a symbol link from $(LINK_TARGET) to $(LINK) in $(bindir) failed: \`$(bindir)/$(LINK)' already exists"; \
+-	   echo "Perhaps remove \`$(bindir)/$(LINK)' manually?"; \
++	   echo "Creating a symbol link from $(LINK_TARGET) to $(LINK) in $(DESTDIR)$(bindir) failed: \`$(DESTDIR)$(bindir)/$(LINK)' already exists"; \
++	   echo "Perhaps remove \`$(DESTDIR)$(bindir)/$(LINK)' manually?"; \
+ 	   exit 1; \
+ 	 fi;
+ 
+@@ -751,10 +751,10 @@
  # from the installation itself.
  #
  install-dirs ::
@@ -29,7 +56,7 @@
  
  # Better do this first...
  # but we won't for the moment, do it on-demand from
-@@ -682,10 +682,10 @@
+@@ -791,10 +791,10 @@
  INSTALL_PROGS := $(foreach p, $(INSTALL_PROGS), $(addsuffix $(subst _,,$(subst __,$(exeext),_$(suffix $(p))_)), $(basename $(p))))
  
  install:: $(INSTALL_PROGS)
@@ -43,7 +70,7 @@
  	done
  endif
  
-@@ -695,40 +695,40 @@
+@@ -804,40 +804,40 @@
  #
  ifneq "$(INSTALL_SCRIPTS)" ""
  install:: $(INSTALL_SCRIPTS)
@@ -95,7 +122,7 @@
  		esac; \
  	done
  endif
-@@ -741,25 +741,25 @@
+@@ -850,25 +850,25 @@
  INSTALL_LIBEXECS := $(foreach p, $(INSTALL_LIBEXECS), $(addsuffix $(subst _,,$(subst __,$(exeext),_$(suffix $(p))_)), $(basename $(p))))
  
  install:: $(INSTALL_LIBEXECS)
@@ -127,16 +154,37 @@
  	done
  endif
  
-@@ -805,9 +805,9 @@
- #
- ifneq "$(SCRIPT_LINK)" ""
- install ::
--	@if ( $(PERL) -e '$$fn="$(bindir)/$(SCRIPT_LINK)"; exit ((! -f $$fn || -l $$fn) ? 0 : 1);' ); then \
-+	@if ( $(PERL) -e '$$fn="$(DESTDIR)$(bindir)/$(SCRIPT_LINK)"; exit ((! -f $$fn || -l $$fn) ? 0 : 1);' ); then \
- 	   echo "Creating a symbol link from $(SCRIPT_PROG) to $(SCRIPT_LINK) in $(bindir)"; \
--	   $(RM) $(bindir)/$(SCRIPT_LINK); \
--	   $(LN_S) $(SCRIPT_PROG) $(bindir)/$(SCRIPT_LINK); \
-+	   $(RM) $(DESTDIR)$(bindir)/$(SCRIPT_LINK); \
-+	   $(LN_S) $(SCRIPT_PROG) $(DESTDIR)$(bindir)/$(SCRIPT_LINK); \
- 	 else \
- 	   echo "Creating a symbol link from $(SCRIPT_PROG) to $(SCRIPT_LINK) in $(bindir) failed: \`$(bindir)/$(SCRIPT_LINK)' already exists"; \
+@@ -878,26 +878,26 @@
+ uninstall:: 
+ 	@for i in $(INSTALL_PROGS) "" ; do			\
+ 	  if test "$$i"; then 					\
+-		echo rm -f $(bindir)/`basename $$i`;		\
+-		rm -f $(bindir)/`basename $$i`;			\
++		echo rm -f $(DESTDIR)$(bindir)/`basename $$i`;		\
++		rm -f $(DESTDIR)$(bindir)/`basename $$i`;			\
+ 	  fi; 							\
+ 	done
+ 	@for i in $(INSTALL_LIBS) ""; do			\
+ 	  if test "$$i"; then 					\
+-		echo rm -f $(libdir)/`basename $$i`;		\
+-		rm -f $(libdir)/`basename $$i`;			\
++		echo rm -f $(DESTDIR)$(libdir)/`basename $$i`;		\
++		rm -f $(DESTDIR)$(libdir)/`basename $$i`;			\
+ 	  fi;							\
+ 	done
+ 	@for i in $(INSTALL_LIBEXECS) ""; do			\
+ 	  if test "$$i"; then 					\
+-		echo rm -f $(libexecdir)/`basename $$i`;	\
++		echo rm -f $(DESTDIR)$(libexecdir)/`basename $$i`;	\
+ 		rm -f $(libexecdir)/`basename $$i`;		\
+ 	  fi;							\
+ 	done
+ 	@for i in $(INSTALL_DATAS) ""; do			\
+ 	  if test "$$i"; then 					\
+-		echo rm -f $(datadir)/`basename $$i`;		\
+-		rm -f $(datadir)/`basename $$i`;		\
++		echo rm -f $(DESTDIR)$(datadir)/`basename $$i`;		\
++		rm -f $(DESTDIR)$(datadir)/`basename $$i`;		\
+ 	  fi;							\
+ 	done
+ 
